- README.md
- Sources/Builder.swift
- Sources/Document.swift
- Sources/InContextError.swift
- Sources/Renderers/IdentityRenderer.swift
- Sources/Renderers/RenderManager.swift
- Sources/Renderers/Renderer.swift
- Sources/Renderers/StencilRenderer.swift
- Sources/Renderers/TiltRenderer.swift
- Sources/Stencil/CachingLoader.swift
- Sources/TemplateCache.swift
- Sources/TemplateDetails.swift
- Sources/TemplateStatus.swift
- Sources/TemplateTracker.swift
This change also introduces a top-level `RenderManager` which is responsible for dispatching renders to different `Renderer` instances.
> refactor: Inject the template cache into renderers

- Sources/Builder.swift
- Sources/Extensions/Array.swift
- Sources/Extensions/String.swift
- Sources/Importers/ImageImporter.swift
- Sources/Importers/MarkdownImporter.swift
- Sources/InContextError.swift
- Sources/RenderTracker.swift
- Sources/Renderers/RenderManager.swift
- Sources/Renderers/StencilRenderer.swift
- Sources/Site.swift
- Sources/Stencil/Executable.swift
- Sources/Store/Store.swift
This change also includes a drive-by refactor to rename `TemplateTracker` to `RenderTracker`.
> fix: Replace `InContextError.unknown` with more informative errors

- Sources/Builder.swift
- Sources/Contexts/DocumentContext.swift
- Sources/Store/QueryDescription.swift
- Sources/Store/QueryTracker.swift
- Sources/Store/Store.swift
- Sources/Transforms/ImageDocumentTransform.swift
- Sources/Transforms/RelativeSourceTransform.swift
- Sources/Transforms/Transformer.swift
This change also moves some of the document context construction into `QueryTracker` to avoid having to perform that at every call-site.
> feat: Expose a generic query to the templates

- Sources/Contexts/DocumentContext.swift
- Sources/Importers/ImageImporter.swift
This change also includes a drive-by fix to stub-out the `previous` and `next` page methods.
> fix: Import image descriptions and locations

- Sources/Contexts/DocumentContext.swift
- Sources/Extensions/Dictionary.swift
- Sources/InContextError.swift
- Sources/Utilities/Callable.swift
- Sources/Utilities/Candidates.swift
- Sources/Utilities/Function.swift
This change includes a drive-by refactor to clean up the `DocumentContext` symbol and function lookup.
> fix: Improve error reporting when calling context functions with incorrect arguments

- README.md
- Sources/Builder.swift
- Sources/Contexts/DocumentContext.swift
- Sources/RenderTracker.swift
We should be able to use these to track inline template renders when cleaning up the HTML.
> fix: Expose (and use) render methods directly on `RenderTracker`

- Sources/Builder.swift
- Sources/Command.swift
- Sources/Extensions/String.swift
- Sources/Extensions/URL.swift
- Sources/Importers/ImageImporter.swift
- Sources/Site.swift
- Sources/Transforms/ImageDocumentTransform.swift
- Sources/Utilities/TaskRunner.swift
This change updates the hard-coded rule set to honour input formats for everything except TIFF and HEIC which are always transformed to JPEG.
> fix: Support richer image transform rules

- Scripts/run.sh
- Sources/Importers/ImageImporter.swift
This addresses a bug where image scales were too small.
> fix: Always generate thumbnails instead of using file metadata

- README.md
- Sources/Contexts/DocumentContext.swift
- Sources/Importers/ImageImporter.swift
- Sources/Utilities/EXIF.swift
This change also includes a small fix to the `resolve` context function to support resolving '.'.
> fix: Include the optional image projection in the document metadata

- README.md
- Sources/Builder.swift
- Sources/Document.swift
- Sources/Extensions/Array.swift
- Sources/Extensions/Bool.swift
- Sources/Extensions/Dictionary.swift
- Sources/Extensions/Double.swift
- Sources/Extensions/Float.swift
- Sources/Extensions/Int.swift
- Sources/Extensions/String.swift
- Sources/Importers/CopyImporter.swift
- Sources/Importers/ImageImporter.swift
- Sources/Importers/Importer.swift
- Sources/Importers/MarkdownImporter.swift
- Sources/Importers/VideoImporter.swift
- Sources/RenderStatus.swift
- Sources/RenderTracker.swift
- Sources/Store/Store.swift
- Sources/Utilities/Fingerprint.swift
- Sources/Utilities/Fingerprintable.swift
- Tests/ic3tests/Tests/ImageImporterTests.swift
- Tests/ic3tests/Tests/MarkdownImporterTests.swift
This fixes a significant issue where per-import settings changes did not trigger a re-render.
> fix: Use document content fingerprints to track render changes

- Sources/AnyHandler.swift
- Sources/Builder.swift
- Sources/FrontmatterDocument.swift
- Sources/Handler.swift
- Sources/Importers/CopyImporter.swift
- Sources/Importers/IgnoreImporter.swift
- Sources/Importers/ImageImporter.swift
- Sources/Importers/Importer.swift
- Sources/Importers/MarkdownImporter.swift
- Sources/Importers/VideoImporter.swift
- Tests/ic3tests/Extensions/Utilities.swift
- Tests/ic3tests/Resources/2022-05-31-17-55-03-royal-wave.mov
- Tests/ic3tests/Tests/ImageImporterTests.swift
- Tests/ic3tests/Tests/MarkdownImporterTests.swift
- Tests/ic3tests/Tests/VideoImporterTests.swift
Photos.app on macOS historically only lets you type 'line separator' characters (not new lines) into the caption field, meaning that they weren't parsing correctly. This change updates `Frontmatter` to permit these characters by simply treating them as new lines.
This change also includes a drive-by refactor to simplify what's passed to importers to make them easier to test and, long-term, make them simpler to implement.
> fix: Support line separator as an alternative to new lines in Frontmatter

- Sources/InContextCore/Builder.swift
- Sources/InContextCore/RenderTracker.swift
- Sources/InContextCore/Settings.swift
- Sources/InContextCore/Site.swift
- Tests/InContextTests/Tests/ImageImporterTests.swift
- Tests/InContextTests/Tests/MarkdownImporterTests.swift
This change exposes the title and url from 'site.yaml' to the renderer.
> fix: Initial work to add structured site settings

- Sources/InContextCore/Renderers/TiltRenderer.swift
- Sources/InContextCore/Utilities/ArgumentProvider.swift
- Sources/InContextCore/Utilities/Callable.swift
- Sources/InContextCore/Utilities/Candidates.swift
- Sources/InContextCore/Utilities/Function.swift
Which allows LuaArgumentProvider to stop guessing the types of strings and tables (using toany() with guessType=true). This also simplifies things a little.
> Add strong typing of arguments to ArgumentProvider

- InContext/InContext.xcodeproj/xcshareddata/xcschemes/InContext.xcscheme
- Sources/InContextCore/Site.swift
'build-swift' was always intended to be a temporary thing.
> fix: Use 'build' as the build directory instead of 'build-swift'

- README.md
- templates.md
This change also fleshes out some of the template documentation.
> fix: Move `titlecase` render function into the `incontext` namespace

- .gitmodules
- Package.swift
This change switches to using a custom fork of Hummingbird. It's technically unnecessary since Hummingbird has accepted the required SVG fix, but it will help shield against unnecessary changes in the project and ease other fixes in the future.
> fix: Ensure SVGs display correctly in Safari

- README.md
- Sources/InContextCore/Builder.swift
- Sources/InContextCore/Importers/CopyImporter.swift
- Sources/InContextCore/Importers/EmptySettings.swift
- Sources/InContextCore/Importers/IgnoreImporter.swift
- Sources/InContextCore/Importers/ImageImporter.swift
- Sources/InContextCore/Importers/MarkdownImporter.swift
- Sources/InContextCore/Importers/VideoImporter.swift
- Sources/InContextCore/Server.swift
- Sources/InContextCore/Settings.swift
- Sources/InContextCore/Site.swift
- Tests/InContextTests/Tests/ImageImporterTests.swift
- Tests/InContextTests/Tests/MarkdownImporterTests.swift
- docs/content/css/main.css
- docs/content/docs/configuration.md
- docs/site.yaml
This change adopts the type-safe configuration for most of 'site.yaml' and cleans up the definition of the importer steps. It represents a breaking change to the configuration and, as such, bumps the configuration version to 2. This is preparatory work for extracting path generation and defaults to a top-level structure that can be shared between importers to simplify settings.
> fix: Clean up the import configuration

- docs/content/docs/templates/index.md
- docs/content/index.markdown
- docs/templates/common.lua
- docs/templates/home.html
This also includes a couple of drive-by documentation style fixes.
> docs: Document `document.closestAncestor()`

- InContext/Helper/Helper.entitlements
- README.md
This change allows the Helper app to access all folders referenced in the site configuration and actions, and addresses issues of behavioural differences between the Helper and command-line app.
> fix: Remove the Helper app sandbox

- InContext/Helper/Model/SiteModel.swift
Using the default task priority for background builds leaves the UI unresponsive during builds. Reducing this to `.background` will slow builds but leaves the app responsive.
> fix: Reduce priority of background builds

- Sources/InContextCore/Builder.swift
- Sources/InContextCore/Extensions/Date.swift
- Sources/InContextCore/Store/Store.swift
Using full nanosecond precision to track file modification times seems to be broken on Sonoma meaning files always show as modified leading to unnecessary work. This change reduces modification time checks to milliseconds and explicitly uses milliseconds when storing modification times in the intermediate SQLite store.
Nanosecond granularity comparisons did seem to infrequently break pre-Sonoma (see #159) but it's concerning to me the behaviour seems so different on Sonoma.
> fix: Use millisecond granularity when tracking file modification times

- .gitmodules
- Package.resolved
- Package.swift
- Sources/InContextCore/Extensions/String.swift
- Sources/InContextCore/Utilities/Hoedown.swift
- Tests/InContextTests/Tests/FrontmatterTests.swift
- Tests/InContextTests/Tests/MarkdownTests.swift
This change switches over from MarkdownKit to Hoedown and implements custom header rendering behaviour to ensure we still provide support for header anchors.
> fix: Support Markdown footnotes

- .github/workflows/build.yaml
- notarization-response.json
This fixes an issue where download-artifacts@master step was unable to see the artifacts uploaded with upload-artifacts@v3.
This change includes a drive-by fix to remove the transient 'notarization-response.json' which was added in error.
> ci: Use consistent artifact upload and download actions

- Package.swift
- Sources/InContextCore/Extensions/Date.swift
- Sources/InContextCore/Extensions/URL.swift
- Sources/InContextCore/ImageTransform.swift
- Sources/InContextCore/Renderers/RenderManager.swift
- Sources/InContextCore/Site.swift
- Sources/InContextCore/TemplateIdentifier.swift
- Sources/PlatformSupport/PlatformSupport.swift
- Tests/InContextTests/Extensions/Date.swift
This switches from importing `UniformTypeIdentifiers` to `PlatformSupport` which will provide a shim replacement for `UTType` on Linux.
> refactor: Adopt the new cross-platform `PlatformSupport` module

- InContext/InContext.xcodeproj/project.pbxproj
- docs/templates/navigation.html
This somehow kept the 'incontext-waialua' name from the old repository.
> refactor: Rename the incontext package name in the Xcode project

- README.md
The one remaining improvement listed is now tracked by #274.
> docs: Remove 'Improvements' section from the readme

- scripts/build.sh
It looks like there's a bug in the latest SwiftPM which causes it to generate two module maps for CLua (one for the tool, and one for the library) and then, in the outer package, see those as duplicate definitions. Xcode still manages to build the project just fine though (typical), so this change disables the `swift build` and `swift test` steps, leaving the work to Xcode which we're already using to build and package the InContext helper and CLI. Of course it sucks because it means we loose all our automated testing, but it's better than a project that doesn't build at all.
> ci: Work-around build issues relating to duplicate CLua definitions

- docs/content/CNAME
This is a legacy from earlier GitHub Pages hosting.
> chore: Remove unused CNAME file
